{"uuid": "299f7932-cb05-4235-b32c-cace3acdc12a", "children": ["e6bd8ac7-7dc6-43a7-82af-99de6e64b091"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of Microsoft Edge WebDriver only supports Microsoft Edge version 125\nCurrent browser version is 127.0.2651.86 with binary path C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe\nStacktrace:\n\tGetHandleVerifier [0x00007FF70F6E5DC2+61250]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF70F6706C9+206985]\n\t(No symbol) [0x00007FF70F47E3C7]\n\t(No symbol) [0x00007FF70F4B681F]\n\t(No symbol) [0x00007FF70F4B5CD8]\n\t(No symbol) [0x00007FF70F4B0360]\n\t(No symbol) [0x00007FF70F4ACDE7]\n\t(No symbol) [0x00007FF70F4EE9DC]\n\t(No symbol) [0x00007FF70F4E4563]\n\t(No symbol) [0x00007FF70F4B9FCE]\n\t(No symbol) [0x00007FF70F4B918C]\n\t(No symbol) [0x00007FF70F4B9B81]\n\tMicrosoft::Applications::Events::EventProperty::to_string [0x00007FF70F89DF54+1072532]\n\t(No symbol) [0x00007FF70F532D9C]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF70F5DEF4C+51468]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF70F5D3805+4549]\n\tMicrosoft::Applications::Events::EventProperty::to_string [0x00007FF70F89CF15+1068373]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF70F67A0D1+246417]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF70F675434+226804]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF70F67556B+227115]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF70F66BD60+188192]\n\tBaseThreadInitThunk [0x00007FFAC5717374+20]\n\tRtlUserThreadStart [0x00007FFAC771CC91+33]\n\n", "trace": "  File \"C:\\Users\\Administrator\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\_pytest\\fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\Documents\\笔记\\课件+笔记\\web_pytest_framework\\testcases\\conftest.py\", line 15, in login\n    driver = webdriver.Edge(service=e)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\selenium\\webdriver\\edge\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 208, in __init__\n    self.start_session(capabilities)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 292, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1723102200000, "stop": 1723102203302}], "start": 1723102200000, "stop": 1723102203377}